services:
  - type: web
    name: epharmacy-server
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://epharmacy-dashboard.onrender.com
      - key: PROD_CLIENT_URL
        value: https://epharmacy-dashboard.onrender.com
    healthCheckPath: /healthz
