services:
  - type: web
    name: admin-dashboard
    env: node
    buildCommand: npm install --include=dev && npx prisma generate && npm run clean && npm run build && cp -r prisma dist/prisma
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://admin-dashboard-iota-seven-29.vercel.app
      - key: PROD_CLIENT_URL
        value: https://admin-dashboard-iota-seven-29.vercel.app
      - key: RENDER_SKIP_LOCKFILE_CHECK
        value: true
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,http://localhost:3000,http://localhost:5174,https://admin-dashboard-iota-seven-29.vercel.app
    healthCheckPath: /graphql
